---
- name: testtt
  hosts: mysite
 

  vars:
    dest_folder: /home/rmsuser/folder1
    mytext2: "Privetttt!"

  tasks:

  - name: Create filestt 
    copy:
     dest: /home/rmsuser/testtt2.txt
     content:
        "Tline1\n
        Tline2 bn filestt\n
        Hi, {{mytext2}}" 
